export const TLD_POSITION = 0;
export const DOMAIN_CHECKED_POSITION = 1;
export const TYPOSQUATTING_SUBDOMAIN_POSITION= 3;
export const TYPOSQUATTING_DOMAIN_POSITION = 2;
export const SCANNED_POSIITON = 4;
