export const shortenURLDomains = [
    'bit.ly',
    'tinyurl.com',
    'shorturl.at',
    't.co', // Twitter
    'goo.gl', // Google (descontinuado, pero aún en uso)
    'ow.ly', // Hootsuite
    'is.gd',
    'buff.ly', // Buffer
    'adf.ly',
    'rebrand.ly',
    'bl.ink',
    'cutt.ly',
    'shorte.st',
    'mcaf.ee', // McAfee
    'lnkd.in', // LinkedIn
    'fb.me', // Facebook
    'trib.al',
    'bit.do',
    'v.gd',
    'qr.ae',
    't.ly',
    'rb.gy',
    'clck.ru',
    's.id',
    'chilp.it',
    'u.to',
    'x.co',
    '1url.com',
    't2m.io',
    'yourls.org',
    'po.st',
    'bc.vc',
    'ity.im',
    'linktr.ee', 
    'short.cm',
    'snip.ly',
    'tny.im',
    'short.io',
    'cutt.us',
    'v.ht',
    'kutt.it',
    'shrtco.de',
    'tini.cc',
    't1p.de',
    'gg.gg',
    '2u.pw',
    'l.ead.me',
    'zpr.io',
    'smarturl.it',
    'lnk.to',
    'lnk.bio',
    'plink.to',
];
